[project]
name = "tcp-client-server"
version = "0.1.0"
description = "Python TCP Client & Server"
authors = [
    {name = "Aolin", email = "aolinz@outlook.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
